trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Build Job'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.17'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Install Dependencies and Build'

          - script: |
              npm test
            displayName: 'Run Tests'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/NestApp.zip'
              replaceExistingArchive: true
            displayName: 'Archive Build Output'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)/NestApp.zip'
              artifactName: 'drop'
              publishLocation: 'Container'
            displayName: 'Publish Artifact'

  - stage: Deploy
    displayName: 'Deploy to Production'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: 'Deploy Job'
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                # Azure Web App Deployment
                - task: AzureWebApp@1
                  displayName: 'Azure Web App Deploy: nestjs-lab-api'
                  inputs:
                    azureSubscription: 'Azure-Abonnement 1 (9bf7d398-40c9-420e-8331-563f3e0dc68f)'
                    appType: 'webApp'
                    appName: 'nestjs-lab-api'
