name: Trigger Azure Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Azure Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Azure Pipeline
        uses: Azure/Pipelines@v2
        with:
          azure-devops-project-url: 'https://dev.azure.com/matghp-org/NestJS-Lab'
          azure-pipeline-name: 'MatGhp.NestJs-Lab'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}

